name: Remove history from Azure Subscription

on:
  push:
    branches:
      - azure-history-remove
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  remove_deployment_history:
    name: Removing deployment history from Azure Subscription

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check date
        id: check_date
        run: |
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          start_date="2023-08-09T00:00:00Z"
          end_date="2023-08-09T00:00:00Z"
          if [[ "$current_date" < "$start_date" || "$current_date" > "$end_date" ]]; then
            echo "Current date is outside the allowed range. Exiting."
            exit 0
          fi

      - name: Set environment variables
        id: variables
        run: |
          $client_secret=${{ secrets.AZM_CLIENT_SECRET }}
          echo "::add-mask::$client_secret"

          echo "client_id=${{ vars.AZM_CLIENT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8
          echo "client_secret=$client_secret" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8
          echo "tenant_id=${{ vars.AZM_TENANT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8
          echo "subscription_id=${{ vars.AZM_SUBSCRIPTION_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal -u ${{ steps.variables.outputs.client-id }} -p ${{ steps.variables.outputs.client-secret }} --tenant ${{ steps.variables.outputs.tenant-id }}

      - name: Remove history
        shell: pwsh
        run: |
          $deploymentlist = az deployment sub list --query "[].name" | ConvertFrom-Json
          $deploymentlist | ForEach-Object {
            $deletedeployment = $_
            az deployment sub delete -n $deletedeployment
          }
