name: Remove history from Azure Subscription

on:
  push:
    branches:
      - azure-history-remove
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  remove_deployment_history:
    name: Removing deployment history from Azure Subscription

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set environment variables
        id: variables
        shell: pwsh
        run: |
          echo "client_id=${{ vars.AZM_CLIENT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8
          echo "tenant_id=${{ vars.AZM_TENANT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8
          echo "subscription_id=${{ vars.AZM_SUBSCRIPTION_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8

      - name: Azure CLI script
        uses: azure/login@v2
        env:
          AZURE_CLIENT_ID: ${{ steps.variables.outputs.client_id }}
          AZURE_TENANT_ID: ${{ steps.variables.outputs.tenant_id }}
          AZURE_SUBSCRIPTION_ID: ${{ steps.variables.outputs.subscription_id }}
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Remove history
        shell: pwsh
        run: |
          $deploymentlist = az deployment sub list --query "[].name" | ConvertFrom-Json
          $deploymentlist | ForEach-Object {
            $deletedeployment = $_
            az deployment sub delete -n $deletedeployment
          }
