name: Remove history from Azure Subscription

on:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  remove deployment history:
    name: Removing deployment history from Azure Subscription

    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        id: variables
        shell: pwsh
        run: |
          echo "client_id= ${{ vars.AZM_CLIENT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "tenant_id= ${{ vars.AZM_TENANT_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "subscription_id= ${{ vars.AZURE_SUBSCRIPTION_ID }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

      - name: Azure Login
        uses: azure/cli@v1
        with:
          client-id: ${{ steps.variables.outputs.client_id }}
          tenant-id: ${{ steps.variables.outputs.tenant_id }}
          subscription-id: ${{ steps.variables.outputs.subscription_id }}}

      - name: Remove history
        shell: pwsh
        run: |
          $deploymentlist = az deployment sub list --query "[].name" | ConvertFrom-Json
          $deploymentlist | ForEach-Object {
            $deletedeployment = $_
            az deployment sub delete -n $deletedeployment
          }