name: On Team Topic Verified

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue number'
        required: true
        default: ''
      verified:
        description: 'Value indicating whether the verification process is successful or not'
        required: true
        default: 'false'

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  verification-start:
    name: 'Completing verification'

    runs-on: ubuntu-latest

    steps:
    # - name: Check event payload
    #   shell: pwsh
    #   run: |
    #     $eventPayload = ${{ toJson(github) }}

    - name: Check issue details
      id: issue
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        echo "number=${{ github.event.inputs.issue-number }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8

        $issue = $(gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue-number }} | ConvertFrom-Json)
        echo "title=$($issue.title)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

        echo "githubId=$($issue.user.login)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
        echo "assignee=$($issue.assignee)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

    - name: Check team name
      id: team
      shell: pwsh
      run: |
        $title = "${{ steps.issue.outputs.title }}"
        $teamName = $title.Contains("]") ? $title.Substring(0, $title.IndexOf(']')).Replace("[", "").Replace("]", "").Trim().ToLowerInvariant() : ""

        echo "name=$teamName" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

    - name: Add a label - NOT Verified
      if: github.event.inputs.verified == 'false'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue edit ${{ steps.issue.outputs.number }} \
          --add-label "invalid" \
          -R ${{ github.event.repository.full_name }}

    - name: Comment to issue - NOT Verified
      if: github.event.inputs.verified == 'false'
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-comment'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ steps.issue.outputs.number }}
        emoji: 'confused,eyes'
        body: |
          👋🏼 @${{ steps.issue.outputs.githubId }} 님!

          주제 제출을 확인하는 과정에서 문제가 발생했습니다. 😢

          곧바로 사무국을 찾아가서 문제를 해결해주세요. 🙏

    - name: Add a label - Verified
      if: github.event.inputs.verified == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue edit ${{ steps.issue.outputs.number }} \
          --add-label "verified" \
          --remove-label "verifying,invalid" \
          -R ${{ github.event.repository.full_name }}

    - name: Comment to issue - Verified
      if: github.event.inputs.verified == 'true'
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-comment'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ steps.issue.outputs.number }}
        emoji: 'hooray'
        body: |
          👋🏼 @${{ steps.issue.outputs.githubId }} 님!

          해커톤 주제 확인이 끝났습니다. 축하드립니다! 🎉

          이제 바로 애플리케이션 개발을 시작해 주세요. 더 중요한 다음 라운드가 다가오고 있습니다! 💪
          
          부지런히 코딩하고, 팀원들과 소통하며, 더 좋은 결과물을 만들어봅시다. 🚀 그리고 필요하면 기술 멘토님과 비기술 멘토님들께 도움을 요청하세요. 🙏

    - name: Close issue - Verified
      if: github.event.inputs.verified == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue close ${{ steps.issue.outputs.number }} \
          -c "주제 제출을 확인했습니다. 이슈를 닫습니다." \
          -R ${{ github.event.repository.full_name }}
